name: Standalone OSAL Build and Test

on:
  push:
  pull_request:

env:
  PERMISSIVE_MODE: true
  REPO_NAME: ${{ github.event.repository.name }}

jobs:

  prep-env:
    name: Prepare Environment
    runs-on: ubuntu-18.04

    steps:
      - name: Cache Source and proto-build
        id: cache-src-proto-bld
        uses: actions/cache@v2
        with:
          path: /home/runner/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/*
          key: proto-build-${{ github.run_number }}

      - name: Checkout OSAL
        if: steps.cache-src-proto-bld.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
      - name: Copy Makefile
        run: ls
      - name: Copy Makefile
        run: |
          cd osal
          ls
      - name: Copy Makefile
        run: cp osal/Makefile.sample Makefile

      - name: Prep Build
        run: |
          make PERMISSIVE_MODE=true prep 

  build-osal:
    runs-on: ubuntu-18.04
    needs: prep-env

    steps:
      - name: Cache Source and proto-build
        id: cache-src-proto-bld
        uses: actions/cache@v2
        with:
          path: /home/runner/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/*
          key: proto-build-${{ github.run_number }}

      - name: Build the code
        run: make -j


  build-tests:
    runs-on: ubuntu-18.04
    needs: [prep-env, build-osal]
    env:
      ENABLE_UNIT_TESTS: true

    steps:

      - name: Install lcov
        run: sudo apt-get install lcov -y

      - name: Cache Source and proto-build
        id: cache-src-proto-bld
        uses: actions/cache@v2
        with:
          path: /home/runner/work/${{ env.REPO_NAME }}/${{ env.REPO_NAME }}/*
          key: proto-build-${{ github.run_number }}

      - name: Prep Tests
        run: |
          make prep

      - name: Check files post bin-build
        run: ls

      - name: Build Tests Binary
        run: make -j

      - name: Run Tests
        run: make test

  #
  # Run-Unit-Tests:
  #   runs-on: ubuntu-18.04
  #   timeout-minutes: 15
  #   needs: "Prepare-Environment"
  #
  #   steps:
  #     - name: Install coverage tools
  #       run: sudo apt-get install lcov -y
  #
  #     - name: Prepare the test environment
  #       run: make PERMISSIVE_MODE=true ENABLE_UNIT_TESTS=true prep
  #
  #     # Baseline lcov and run all tests
  #     - name: Test
  #       run: make test
  #
  #     - name: Calculate coverage
  #       run: make lcov | tee lcov_out.txt
  #
  #     - name: Confirm 100% line coverage
  #       run: |
  #         if [[ `grep -A 3 "Overall coverage rate" lcov_out.txt | grep lines` != *"100.0%"* ]]; then
  #           grep -A 3 "Overall coverage rate" lcov_out.txt
  #           echo "Lacks 100.0% line unit test coverage"
  #           exit -1
  #         fi
